FROM node:lts-bullseye
RUN npm config set registry https://registry.npmmirror.com
RUN pnpm setup
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH=$PNPM_HOME:$PATH
RUN npm install -g pnpm
RUN npm install -g yarn
RUN npm config set strict-ssl false
