services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      # 集群中本 broker 的ID
      KAFKA_BROKER_ID: 1
      
      # 指定 Zookeeper 地址
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
      # 宿主机访问 Kafka 时的地址(IP或域名根据需要而定)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      
      # 如果只有一个Broker，请将副本因子设置为 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
